readable_col_names = {
    "cumulative_cases": "Cumulative Cases",
    "cumulative_deaths": "Cumulative Deaths",
    "current_hospitalizations": "Hospitalizations",
    # "cases_active": "Active Cases",
    "daily_deaths": "Daily Deaths",
    "daily_cases": "Daily Cases",
    "daily_reported_cases": "Daily Reported Cases",
    "cumulative_reported_cases": "Cumulative Reported Cases",
    "current_vent_usage": "Current Ventilator Usage",
    "R_eff": "Effective Reproductive Number (Reff)",
    # "cases_per_100k": "Active Cases per 100k",
    "active_asymptomatic_cases": "Active Asymptomatic Cases",
    "case_reporting_rate": "Case Reporting Rate",
    "doubling_t": "Doubling Time",
    "current_icu_usage": "ICU Beds Usage",
    "total_population": "Population",
    "daily_hospitalizations": "Incident Hospitalizations",
}
