"""Defines the dict readable_col_names that maps output columsn to plain english."""
readable_col_names = {
    "cumulative_cases": "Cumulative Cases",
    "cumulative_deaths": "Cumulative Deaths",
    "current_hospitalizations": "Hospitalizations",
    # "cases_active": "Active Cases",
    "daily_deaths": "Daily Deaths",
    "daily_cases": "Daily Cases",
    "daily_reported_cases": "Daily Reported Cases",
    "cumulative_reported_cases": "Cumulative Reported Cases",
    "current_vent_usage": "Current Ventilator Usage",
    "R_eff": "Effective Reproductive Number (Reff)",
    # "cases_per_100k": "Active Cases per 100k",
    "active_asymptomatic_cases": "Active Asymptomatic Cases",
    "case_reporting_rate": "Case Reporting Rate",
    "doubling_t": "Doubling Time",
    "current_icu_usage": "ICU Beds Usage",
    "total_population": "Population",
    "daily_hospitalizations": "Incident Hospitalizations",
    "cumulative_reported_cases_per_100k": "Cumulative Reported Cases per 100,000",
    "daily_reported_cases_per_100k": "Daily Reported Cases per 100,000",
    "daily_deaths_per_100k": "Daily Deaths per 100,000",
    "vacc_dose1": "vaccinations (1 dose)",
    "vacc_dose2": "vaccinations (full)",
    "vacc_dose1_65": "vaccinations (1 dose, 65+)",
    "vacc_dose2_65": "vaccinations (full, 65+)",
    "frac_vacc_dose1": "fraction vaccinated (1 dose)",
    "frac_vacc_dose2": "fraction vaccinated (full)",
    "frac_vacc_dose1_65": "fraction vaccinated (1 dose, 65+)",
    "frac_vacc_dose2_65": "fraction vaccinated (full, 65+)",
    "immune": "# people with immunity",
    "immune_65": "65+ people with immunity",
    "frac_immune": "fraction of people with immunity",
    "frac_immune_65": "fraction of 65+ people with immunity",
    "state_phase": "Current state phase",
}
