readable_col_names = {
    "cumulative_cases": "Cumulative Cases",
    "cumulative_deaths": "Cumulative Deaths",
    "hospitalizations": "Hospitalizations",
    "cases_active": "Active Cases",
    "daily_deaths": "Daily Deaths",
    "daily_cases": "Daily Cases",
    "daily_cases_reported": "Daily Reported Cases",
    "cumulative_cases_reported": "Cumulative Reported Cases",
    "VENT": "Current Ventilator Usage",
    "Reff": "Effective Reproductive Number (Reff)",
    "cases_per_100k": "Active Cases per 100k",
    "cases_asymptomatic_active": "Active Asymptomatic Cases",
    "CASE_REPORT": "Case Reporting Rate",
    "doubling_t": "Doubling Time",
    "ICU": "ICU Beds Usage",
    "N": "Population",
}
